### ISSUE TITLE
Library doesn't compile with GCC 4.8.5 on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by ivanp2015** [HowardHinnant/date#26]
Ubuntu 14.04 is widely used platform nowadays. Standard compiler on it at the moment is GCC 4.8.5. The library just does not compile with it, which make library useless for many users on this platform. Please consider making library buildable in the non-cutting-edge C++11/C++14 compilers, which still widely used. 

Sample output:

ivan@xubuntu1404:~/proexp/date$ g++ --version
g++ (Ubuntu 4.8.5-1ubuntu1~14.04) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ivan@xubuntu1404:~/proexp/date$ g++ -c -std=gnu++11 tz.cpp
tz.cpp: In static member function ‘static void date::Rule::split_overlaps(std::vector<date::Rule>&)’:
tz.cpp:1176:38: error: no matching function for call to ‘std::vector<date::Rule>::erase(__gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >&, __gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >&)’
             rules.erase(first_rule, t);
                                      ^
tz.cpp:1176:38: note: candidates are:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from /usr/include/c++/4.8/bits/random.h:34,
                 from /usr/include/c++/4.8/random:50,
                 from /usr/include/c++/4.8/bits/stl_algo.h:65,
                 from /usr/include/c++/4.8/algorithm:62,
                 from tz.h:55,
                 from tz_private.h:26,
                 from tz.cpp:24:
/usr/include/c++/4.8/bits/vector.tcc:134:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator) [with _Tp = date::Rule; _Alloc = std::allocator<date::Rule>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = date::Rule*]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:134:5: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8/bits/vector.tcc:146:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::iterator) [with _Tp = date::Rule; _Alloc = std::allocator<date::Rule>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = date::Rule*]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:146:5: note:   no known conversion for argument 1 from ‘__gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >’ to ‘std::vector<date::Rule>::iterator {aka __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >}’
tz.cpp:1185:37: error: no matching function for call to ‘std::vector<date::Rule>::erase(__gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >&, __gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >&)’
             rules.erase(t, last_rule);
                                     ^
tz.cpp:1185:37: note: candidates are:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from /usr/include/c++/4.8/bits/random.h:34,
                 from /usr/include/c++/4.8/random:50,
                 from /usr/include/c++/4.8/bits/stl_algo.h:65,
                 from /usr/include/c++/4.8/algorithm:62,
                 from tz.h:55,
                 from tz_private.h:26,
                 from tz.cpp:24:                                                                                                                                                                                                  
/usr/include/c++/4.8/bits/vector.tcc:134:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator) [with _Tp = date::Rule; _Alloc = std::allocator<date::Rule>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = date::Rule*]                                                                     
     vector<_Tp, _Alloc>::                                                                                                                                                                                                        
     ^                                                                                                                                                                                                                            
/usr/include/c++/4.8/bits/vector.tcc:134:5: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8/bits/vector.tcc:146:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::iterator) [with _Tp = date::Rule; _Alloc = std::allocator<date::Rule>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = date::Rule*]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:146:5: note:   no known conversion for argument 1 from ‘__gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >’ to ‘std::vector<date::Rule>::iterator {aka __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >}’
ivan@xubuntu1404:~/proexp/date$

**Comment by rbock** [comment]
Please try -std=c++11 instead of -std=g++11

**Comment by ivanp2015** [comment]
Doesn't compile, just doesn't compile. -std=c++11 is subset of -std=g++11, so I even did not expect the effect.

ivan@xubuntu1404:~/proexp/date$ g++ -std=c++11 tz.cpp
tz.cpp: In static member function ‘static void date::Rule::split_overlaps(std::vector<date::Rule>&)’:
tz.cpp:1176:38: error: no matching function for call to ‘std::vector<date::Rule>::erase(__gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >&, __gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >&)’
             rules.erase(first_rule, t);
                                      ^
tz.cpp:1176:38: note: candidates are:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from /usr/include/c++/4.8/bits/random.h:34,
                 from /usr/include/c++/4.8/random:50,
                 from /usr/include/c++/4.8/bits/stl_algo.h:65,
                 from /usr/include/c++/4.8/algorithm:62,
                 from tz.h:55,
                 from tz_private.h:26,
                 from tz.cpp:24:
/usr/include/c++/4.8/bits/vector.tcc:134:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator) [with _Tp = date::Rule; _Alloc = std::allocator<date::Rule>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = date::Rule*]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:134:5: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8/bits/vector.tcc:146:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::iterator) [with _Tp = date::Rule; _Alloc = std::allocator<date::Rule>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = date::Rule*]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:146:5: note:   no known conversion for argument 1 from ‘__gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >’ to ‘std::vector<date::Rule>::iterator {aka __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >}’
tz.cpp:1185:37: error: no matching function for call to ‘std::vector<date::Rule>::erase(__gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >&, __gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >&)’
             rules.erase(t, last_rule);
                                     ^
tz.cpp:1185:37: note: candidates are:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from /usr/include/c++/4.8/bits/random.h:34,
                 from /usr/include/c++/4.8/random:50,
                 from /usr/include/c++/4.8/bits/stl_algo.h:65,
                 from /usr/include/c++/4.8/algorithm:62,
                 from tz.h:55,
                 from tz_private.h:26,
                 from tz.cpp:24:
/usr/include/c++/4.8/bits/vector.tcc:134:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator) [with _Tp = date::Rule; _Alloc = std::allocator<date::Rule>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = date::Rule*]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:134:5: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8/bits/vector.tcc:146:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::iterator) [with _Tp = date::Rule; _Alloc = std::allocator<date::Rule>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = date::Rule*]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:146:5: note:   no known conversion for argument 1 from ‘__gnu_cxx::__normal_iterator<const date::Rule*, std::vector<date::Rule> >’ to ‘std::vector<date::Rule>::iterator {aka __gnu_cxx::__normal_iterator<date::Rule*, std::vector<date::Rule> >}’

**Comment by rbock** [comment]
Sorry, I was confused by the

```
$ g++ -c -std=g++11 tz.cpp
g++: error: unrecognized command line option ‘-std=g++11’
```

in your original post.

Also, your compiler output seems to be a bit damaged by being interpreted as markdown. Maybe you can paste it as code block?

From what I can guess, you might want to try replacing `cbegin` with `begin` and `cend` with `end` in that function. See what happens.

**Comment by ivanp2015** [comment]
Thanks, this have helped, but indeed this is design issue. cbegin() returns const_iterator which is assumed to use with const obejcts. The "rules" is not const, it gets modified, so iterators must be non-const as well in order to modify.

**Comment by ivanp2015** [comment]
I suggest to fix this permanently in the library.

**Comment by HowardHinnant** [comment]
This sounds like a reasonable concession to me.  Would you like to prepare a pull request?  Or would you prefer for me to just do it.

Just fyi, this isn't a correctness issue, this is a gcc-4.8 compatibility issue.  The C++11 signature is:
````
iterator erase(const_iterator first, const_iterator last);
````

As written, the function promises to either not modify any individual `Rule`, or completely delete it.

**Comment by ivanp2015** [comment]
Yes, that version of libstdc++ does not support erase with const_iterator, which corresponds to C++03 situation. I will try to make a pull requst - this will be my first pull request on the GitHub :)

**Comment by HowardHinnant** [comment]
Awesome!  Don't worry about it being perfect.  I'm a github newbie too and we can just iterate until we get it right.

**Comment by viboes** [comment]
Do you know if there is a ticket for gcc lib? If not it would be worth creating one.

**Comment by ivanp2015** [comment]
No, I don't know. But please take into account - that is not latest version of GCC and libstdc++.
Maybe in GCC5 this already fixed. But actually, many people stick to Ubuntu 14.04 and its "native" GCC version.

**Comment by HowardHinnant** [comment]
This is already fixed in gcc-5.2.  I'm not sure in which version it got fixed.

**Comment by HowardHinnant** [comment]
Fixed with https://github.com/HowardHinnant/date/commit/386d2b8c9d5363c410bfff64f3346040f4c8e044
