### PR TITLE
Use string_literal for C++11 when possible

### PR DESCRIPTION
**Pull request by tomaszkam**
Merged get_units code for C++11 and C++14, now string_literal are used for all non-custom ratio suffix, that are at most 2 characters [except: decaseconds, minutes, microseconds in char].

This requires to special cases for string_literal, for C++11 mode:
1. Constructor for from string or length 2 (3 elements array)
2. Adding two string literals with size 1.

### CODE REVIEW

**Comment by tomaszkam** [comment]
I have also merged code for decaseconds, microseconds and minutes, as I realized that runtime constructing and concatenation string_literals, is no worse than doing the same thing for runtime sized string (that needs to handle SSO).

I preserved special case, that makes most of the cases constrexpr in C++11.

**Comment by tomaszkam** [comment]
Changed get_untis that combine preffix with 's' to be C++11 constexpr, as 2 letter case is supported in C++11.

**Comment by tomaszkam** [comment]
Please squash commits on merge.

**Comment by tomaszkam** [comment]
For the last commits, I am not sure how do you feel about test testing implementation detail, but I found it to be only way to confirm that we get constexpr things.

**Comment by tomaszkam** [comment]
Also, by adding two additional functions, we can make all standard suffix constexpr in C++11. Want to have your opinion.

**Comment by HowardHinnant** [comment]
I'm getting this unit test failure.  I haven't tracked down the cause yet.
```
/Users/howardhinnant/Development/date
passed 1 tests in /Users/howardhinnant/Development/date/test
passed 8 tests in /Users/howardhinnant/Development/date/test/clock_cast_test
durations_output.pass.cpp:315:18: error: constexpr variable 'integer' must be initialized by a constant expression
  CONSTCD14 auto integer = get_units<char>(std::ratio<123>{});
                 ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/howardhinnant/Development/date/include/date/date.h:7823:19: note: modification of object of const-qualified type
      'const char' is not allowed in a constant expression
            p_[i] = x[i];
                  ^
/Users/howardhinnant/Development/date/include/date/date.h:7874:12: note: in call to 'string_literal(string_literal<CharT, 2UL>{x},
      string_literal<CharT, 4UL>{y})'
    return string_literal<CharT, N1 + N2 - 1>{string_literal<CharT, N1>{x},
           ^
/Users/howardhinnant/Development/date/include/date/date.h:7971:28: note: in call to 'operator+(msl(char{'['}), msl<R::num>())'
    return msl(CharT{'['}) + msl<R::num>() + msl(CharT{']'});
                           ^
/Users/howardhinnant/Development/date/include/date/date.h:8186:12: note: in call to 'msl({})'
    return msl<CharT>(p) + string_literal<CharT, 2>{'s'};
           ^
durations_output.pass.cpp:315:28: note: in call to 'get_units({})'
  CONSTCD14 auto integer = get_units<char>(std::ratio<123>{});
                           ^
```

**Comment by tomaszkam** [comment]
Could you please run the test file against the code before my changes in
C++14 mode. The function referenced was not touched by me.

wt., 19.06.2018, 15:35 użytkownik Howard Hinnant <notifications@github.com>
napisał:

**Comment by HowardHinnant** [comment]
I'm not positive how to interpret "the code before my changes in C++14 mode".  If you specify a commit,  I can test it.  Thanks.

**Comment by HowardHinnant** [comment]
Or do you mean against my current master/HEAD?

**Comment by tomaszkam** [comment]
Yes against current master, suffix were meant to be constexpr in C++14
before my changes.

wt., 19.06.2018, 16:33 użytkownik Howard Hinnant <notifications@github.com>
napisał:

**Comment by HowardHinnant** [comment]
I get the same error, and in more places.

**Comment by HowardHinnant** [comment]
Just tried the same experiment with a tip-of-trunk clang, and it passes.  It looks like we're looking at a clang bug in the version of clang I'm using.

What compiler are you using?

**Comment by tomaszkam** [comment]
clang-5.0 and gcc-7 if I remember correctly, will check once I will have
access to my desktop.

What version you are using?



wt., 19.06.2018, 16:43 użytkownik Tomasz Kamiński <tomaszkam@gmail.com>
napisał:

**Comment by HowardHinnant** [comment]
```
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
```
There's no way I know of to map Apple's clang version to a real clang version.

**Comment by HowardHinnant** [comment]
I'm going to see if I can figure out a workaround.  If I can't, I'll go ahead and commit it anyway.

**Comment by tomaszkam** [comment]
Ok, it also does not work with clang++-5.0 with C++14, and works only with g++-7. I must have missed that.

**Comment by HowardHinnant** [comment]
By "do not work", do you mean that common use cases don't work, or that new, stricter tests are failing?  I don't mind if some tests point out compiler bugs, as long as the lib can still work for more common use cases, including with older compilers.

**Comment by HowardHinnant** [comment]
Very nice!

**Comment by tomaszkam** [comment]
I meant that the new constexpr checking test for integral literal was not working also for clang++-5.0, but I missed that accidentally. But this literal was actually not constexpr on master due compiler bug - may test just exposed that.

However, I found a fix - I create an concatenation result inside of operator+, instead of constructor. Made this operator friend to have access to private value_initializing constructor and _p array.

**Comment by tomaszkam** [comment]
Now I am getting errors from gcc, about multiple definitions of operator+, lets me check on that.

**Comment by HowardHinnant** [comment]
Thanks.  I'm running the full test on Apple's clang now...

**Comment by HowardHinnant** [comment]
Confirmed everything still passes here.  Thanks!

**Comment by tomaszkam** [comment]
Tested on Wandbox - in C++14 mode latest version compiles from g++ 5.1 and clang 3.5 (I have not checked earlier versions).

**Comment by HowardHinnant** [comment]
`<chrono>` itself starts falling apart much earlier than that.

**Comment by tomaszkam** [comment]
Tested C++11 for from gcc 4.9 and clang starting from 3.5. Link: https://wandbox.org/permlink/Hir7y2YjYmJzJJAN
I think we may squash it to master now. Hope that there will be no surprises from MSVC.

**Comment by tomaszkam** [comment]
I have restored few inline specifiers on functors, that I have accidentally dropped.

**Comment by HowardHinnant** [comment]
Merged: https://github.com/HowardHinnant/date/commit/2d282e35fa18119d6d9396813da2cc4ad29a9d5a

Thanks much!  Nice job!
