### ISSUE TITLE
date::parse doesn't work with VS2019 v16.10 anymore

### ISSUE THREAD

**Issue by JulZimmermann** [HowardHinnant/date#676]
Hello,

I just updated my compiler to the current v16.10 release of MSVC and unfortunately, `date::parse` seems not to work anymore.

Take this example (inspired by: https://stackoverflow.com/a/41613816):

```
std::chrono::time_point<std::chrono::system_clock> tp;
std::istringstream("2021-02-18T08:00:00") >> date::parse("%FT%T", tp);
```

This used to compile just fine but now it will give an error:

> error C2672: 'date::parse': no matching overloaded function found
> error C2893: Failed to specialize function template 'unknown-type date::parse(const CharT *,Parsable &)'
> date.h(7883): note: see declaration of 'date::parse'
> note: With the following template arguments:
> note: 'Parsable=std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<std::chrono::system_clock::rep,std::chrono::system_clock::period>>'
> note: 'CharT=char'
> error C2780: 'unknown-type date::parse(const std::basic_string<_Elem,_Traits1,_Alloc1> &,Parsable &,std::basic_string<_Elem,_Traits1,_Alloc1> &,std::chrono::minutes &)': expects 4 arguments - 2 provided
> date.h(7869): note: see declaration of 'date::parse'
> error C2780: 'unknown-type date::parse(const std::basic_string<_Elem,_Traits1,_Alloc1> &,Parsable &,std::chrono::minutes &)': expects 3 arguments - 2 provided
> note: see declaration of 'date::parse'
> error C2780: 'unknown-type date::parse(const std::basic_string<_Elem,_Traits1,_Alloc1> &,Parsable &,std::basic_string<_Elem,_Traits1,_Alloc1> &)': expects 3 arguments - 2 provided
> note: see declaration of 'date::parse'
> error C2784: 'unknown-type date::parse(const std::basic_string<_Elem,_Traits1,_Alloc1> &,Parsable &)': could not deduce template argument for 'const std::basic_string<_Elem,_Traits1,_Alloc1> &' from 'const char [6]'
> note: see declaration of 'date::parse'

**Comment by HowardHinnant** [comment]
I'm afraid this is my fault.  It is a bug in the spec.  I'm trying to [get it fixed](wg21.link/lwg#3554), and the [VS developers are aware](https://github.com/microsoft/STL/issues/1928).

**Comment by JulZimmermann** [comment]
Ok, thanks for the response.

Is there any workaround I could use?

**Comment by HowardHinnant** [comment]
I may have misunderstood your issue.  Can you give me a complete example?  For example are you including "date.h"?

**Comment by JulZimmermann** [comment]
Sure. Here is a complete example:

```

#include <chrono>
#include <iostream>

#include "date/date.h"

int main() {
    std::chrono::time_point<std::chrono::system_clock> tp;
    std::istringstream("2021-02-18T08:00:00") >> date::parse("%FT%T", tp);
}

```

This minimal example doesn't compile with MSVC v16.10 but with v16.9 and lower.
I tested the 3.0.1 and  3.0.0 releases

**Comment by HowardHinnant** [comment]
I don't have an immediate explanation for "`date::parse`: no matching overloaded function found".  

VS is in the process of implementing `std::chrono::parse`, and presumably this error has something to do with that introduction.  However I do not know why `std::chrono::parse` would hide `date::parse` when you've explicitly qualified the call with `date::`.

I note that the date.h line number 7883 doesn't line up with the current date.h at tip of master.  Could you update your date.h to tip of master and re-post the error message?  Thanks.

**Comment by JulZimmermann** [comment]
I updated the library to the current master revision.

Here are the error outputs running the minimal example from above:

> main.cpp(8): error C2672: 'date::parse': no matching overloaded function found
> main.cpp(8): error C2893: Failed to specialize function template 'unknown-type date::parse(const CharT *,Parsable &)'
> date/date.h(8156): note: see declaration of 'date::parse'
> main.cpp(8): note: With the following template arguments:
> main.cpp(8): note: 'Parsable=std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<std::chrono::system_clock::rep,std::chrono::system_clock::period>>'
> main.cpp(8): note: 'CharT=char'
> main.cpp(8): error C2780: 'unknown-type date::parse(const std::basic_string<CharT,Traits,Alloc> &,Parsable &,std::basic_string<CharT,Traits,Alloc> &,std::chrono::minutes &)': expects 4 arguments - 2 provided
> date/date.h(8142): note: see declaration of 'date::parse'
> main.cpp(8): error C2780: 'unknown-type date::parse(const std::basic_string<CharT,Traits,Alloc> &,Parsable &,std::chrono::minutes &)': expects 3 arguments - 2 provided
> date.h(8128): note: see declaration of 'date::parse'
> main.cpp(8): error C2780: 'unknown-type date::parse(const std::basic_string<CharT,Traits,Alloc> &,Parsable &,std::basic_string<CharT,Traits,Alloc> &)': expects 3 arguments - 2 provided
> date/date.h(8116): note: see declaration of 'date::parse'
> main.cpp(8): error C2784: 'unknown-type date::parse(const std::basic_string<CharT,Traits,Alloc> &,Parsable &)': could not deduce template argument for 'const std::basic_string<CharT,Traits,Alloc> &' from 'const char [6]'
> date/date.h(8105): note: see declaration of 'date::parse'

**Comment by HowardHinnant** [comment]
Ok, I've got a theory.  But I'll need your help to test it.

In date.h, line 8157, I'm guessing that
```c++
    -> decltype(from_stream(std::declval<std::basic_istream<CharT>&>(), format, tp),
```
Is finding the new `std::chrono::from_stream`, and not `date::from_stream`.

Does your example work if you modify date.h with a qualification to `date::from_stream`:

```c++
    -> decltype(date::from_stream(std::declval<std::basic_istream<CharT>&>(), format, tp),
```

If that fixes it, I can update date.h right away with this fix.

Thanks.

**Comment by JulZimmermann** [comment]
That did the trick, although changing only this one call was not enough. 

I created #677 to fix the problem.

Thanks a lot for your help!

**Comment by HowardHinnant** [comment]
Thank you!

**Comment by jiggersplat** [comment]
I will add that I switched to std::chrono::system_clock instead of std::chrono::high_resolution_clock and it now compiles and runs fine.

**Comment by HowardHinnant** [comment]
Ah, yes.  `high_resolution_clock` has no relationship to a calendar, whereas `system_clock` does.
